version: '3.8'

services:
  web:
    build: .
    entrypoint: ./entrypoint.dev.sh
    volumes:
      - ./:/opt/po8klasie-fastapi
    ports:
      - 8008:8000
    env_file:
      - ".env${ENV}"
    depends_on:
      - crdb
  crdb:
    image: cockroachdb/cockroach:v22.1.6
    volumes:
      - crdb_data:/cockroach/cockroach-data
    expose:
      - 26257
    ports:
      - 8088:8080
    command: start-single-node --insecure

volumes:
  crdb_data:
