version: '3.8'

services:
  web:
    build: .
    entrypoint: ./entrypoint.dev.sh
    volumes:
      - ./:/opt/po8klasie-fastapi
    ports:
      - 8008:8000
    env_file:
      - ".env${ENV}"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
