version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - ./:/opt/po8klasie-fastapi
    ports:
      - 8008:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/providers/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db

volumes:
  db_data:
